### ISSUE TITLE
A little help for esp32 to esp32 communication

### ISSUE THREAD

**Issue by nathanRamaNoodles** [xXAM22Xx/CANopenESP32#1]
I've ran past your code, but I'm still confused about CANopenNode: [I've open-sourced my code](https://github.com/nathanRamaNoodles/CANopen-ESP32-nodes) which includes yours and others implementations to make a robust CAN esp-idf component for home automation.  So far, I have both esp32 nodes talking but I don't know how to control the object dictionary and PDOs to send a string to the other es32.

I have a couple of questions: 
1. How do you communicate a CAN dataype such as a Domain/string from one esp32 to another esp32 using PDOs and object dictionaries?
    - I've spent a long time, and couldn't find an implementation for both a master and slave.

2. How can you pass messages from master to slave and then from slave to master like a simple chat?

Thanks for any help you are kind enough to provide,
-Nathan Ramanathan

**Comment by Wizcat22** [comment]
Hi,

you can take a look at our object dictionaries (*.xdd / *.eds) or create your own object dictionary with [libedssharp](https://github.com/robincornelius/libedssharp).

There is no big difference between a master and a slave node. The master node has to send NMT commands to set all slaves into "operational"-mode. Our example Nodes are configured as masters. 

In [libedssharp](https://github.com/robincornelius/libedssharp) you can add "Optional Objects" at some index (see [CIA](https://www.can-cia.org/canopen/) for more information). There you can define the datatype and a default value if necessary. Then you have to map this index to one of your RX/TX PDOs.

For a simple chat you create an txPDO (to send data) and a rxPDO (to receive data) in both nodes. The COBID of the txPDO of the first node should be the same as the COBID of the rxPDO of the second node and vice versa. Now you should be able to exchange data between the two nodes.

If you want to send some data between nodes, you simply change the content of your object dictionary variables and request transmission of the corresponding txPDO.

Your receiving nodes should receive the transmitted PDO and update the contents of the variables automatically.

-Alexander Miller

**Comment by nathanRamaNoodles** [comment]
Thank you for responding!

So, in my case I'll have two RXPDOs and two TXPDOs. The first TXPDO (with smaller id, thus higher priority) contains the length of the string, and the second TXPDO contains the actual string segment.  

I also have "TCP like" based questions:

How will the other node know I received the length first and I'm ready to begin receiving the string?  Because by the time I allocate the string, won't I miss one or more responses from the other node?

Does TXPDO and RXPDO use a TCP based approach? 

Is there a possibility in missing a string segment or the order of receiving might be out of order?

How do i know when any of these PDOs are updated (is there a callback when something changes)?

Sorry for asking too many questions.
